name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-southeast-2'

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import (One-time Sync to Backend)
        run: |
          terraform import aws_s3_bucket.rinnah_bucket rinnah-2026-portal || echo "S3 already in state"
          terraform import aws_iam_role.lambda_exec_role rinnah_lambda_execution_role || echo "Role already in state"
          # Adding the Lambda import below:
          terraform import aws_lambda_function.rsvp_lambda rinnah-rsvp-handler || echo "Lambda already in state"
          # Adding the API Gateway import:
          terraform import aws_apigatewayv2_api.rsvp_api x0p16znd81 || echo "API Gateway already in state"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Sync to S3
        run: |
          aws s3 sync .. s3://rinnah-2026-portal --delete \
            --exclude "terraform/*" \
            --exclude ".git/*" \
            --exclude ".github/*"