name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-southeast-2'

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # CLEANUP: Imports are removed because your state is now fully synced in S3
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Sync to S3
        run: |
          aws s3 sync .. s3://rinnah-2026-portal --delete \
            --exclude "terraform/*" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            # --exclude "guests.csv" 

      # CLEANUP: Removed the invalidation step that was causing the exit code 254